sonar.projectKey=onigoetz_rstest-sonar-reporter
sonar.organization=onigoetz
sonar.projectName=rstest-sonar-reporter

sonar.sources=src
sonar.tests=test
sonar.exclusions=node_modules/**

sonar.javascript.lcov.reportPaths=**/coverage/lcov.info
